# FILES
SCRIPT_NAME=cjdscript
BASH_COMPLETION=$(SCRIPT_NAME).bash-completion
README=README.md

# COMMANDS
INSTALL_RX=install -Dm755
INSTALL_RO=install -Dm644
RM=rm -f
RMDIR=rmdir -p --ignore-fail-on-non-empty

# LOCATIONS
PREFIX=/usr
BIN_DIR=$(DESTDIR)$(PREFIX)/bin
DOC_DIR=$(DESTDIR)$(PREFIX)/share/doc/$(SCRIPT_NAME)
BASH_COMPLETION_DIR=$(DESTDIR)$(PREFIX)/share/bash-completion/completions

install:
	$(INSTALL_RX) $(SCRIPT_NAME) $(BIN_DIR)/$(SCRIPT_NAME)
	$(INSTALL_RO) $(BASH_COMPLETION) $(BASH_COMPLETION_DIR)/$(SCRIPT_NAME)
	$(INSTALL_RO) $(README) $(DOC_DIR)/$(README)

uninstall:
	$(RM) $(BIN_DIR)/$(SCRIPT_NAME)
	$(RMDIR) $(BIN_DIR)
	$(RM) $(BASH_COMPLETION_DIR)/$(SCRIPT_NAME)
	$(RMDIR) $(BASH_COMPLETION_DIR)
	$(RM) $(DOC_DIR)/$(README)
	$(RMDIR) $(DOC_DIR)
